#!/usr/bin/env python

from defecttools.irc import defectbot
from defecttools.lib import config

if __name__ == "__main__":
    _config = config.get_config()

    def handler_fn(fd, client):
        data = fd.recv()
        client.send_privmsg(_config.irc_channel, data)

    cmd_fd = defectbot.spawn(_config.irc_server, _config.irc_port,
            _config.irc_nick, _config.irc_password, _config.irc_channel,
            handler_fn)
    while True:
        data = raw_input("Enter text to broadcast:")
        cmd_fd.send(data)
